// export const SET_LOCATION = {
//   SUCCESS: 'SET_LOCATION_SUCCESS',
//   ERROR: 'SET_LOCATION_ERROR',
// };

// export const SET_GATELIST = {
//   SUCCESS: 'SET_GATELIST_SUCCESS',
//   ERROR: 'SET_GATELIST_ERROR',
// };

// export const SYNC_GATE = {
//   SUCCESS: 'SYNC_GATE_SUCCESS',
//   ERROR: 'SYNC_GATE_ERROR',
// };

// export const UPDATE_SCAN_TIME_OF_GATEWAY = {
//   SUCCESS: 'UPDATE_SCAN_TIME_OF_GATEWAY_SUCCESS',
//   ERROR: 'UPDATE_SCAN_TIME_OF_GATEWAY_ERROR',
// };

// export const REMOVE_TIMEDOUT_GATEWAY = {
//   SUCCESS: 'REMOVE_TIMEDOUT_GATEWAY_SUCCESS',
//   ERROR: 'REMOVE_TIMEDOUT_GATEWAY_ERROR',
// };

// export const SET_CURRENT_YARD = {
//   SUCCESS: 'SET_CURRENT_YARD_SUCCESS',
//   ERROR: 'SET_CURRENT_YARD_ERROR',
// };

// export const SET_YARDLIST = {
//   SUCCESS: 'SET_YARDLIST_SUCCESS',
//   ERROR: 'SET_YARDLIST_ERROR',
// };

// export const SET_GATEINSCAN = {
//   SUCCESS: 'SET_GATEINSCAN_SUCCESS',
//   ERROR: 'SET_GATEINSCAN_ERROR',
// };
